AllCops:
  TargetRubyVersion: 2.5.1

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25
  Exclude:
    - spec/**/*
