AllCops:
  TargetRubyVersion: 2.5.1

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25
  Exclude:
    - spec/**/*

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8
